[workspace]
members = [
    "crates/nexa-app",
    "crates/nexa-core",
    "crates/nexa-ooxml",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98.1"
license = "UNLICENSED"
authors = ["Nexa Office contributors"]
repository = "https://github.com/anYuJia/nexa-office"

[workspace.dependencies]
slint = { version = "=1.18.0", default-features = false, features = [
    "std",
    "backend-winit",
    "renderer-software",
    "accessibility",
    "compat-1-18",
] }
slint-build = "=1.18.0"

[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
